management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
  health:
    circuitbreakers:
      enabled: true
server:
  port: 7071
spring:
  application:
    name: clientapp
    
resilience4j:  
 circuitbreaker:    
  instances:      
   fetchFirstApp:
        register-health-indicator: true
        ring-buffer-size-in-closed-state: 6
        ring-buffer-size-in-half-open-state: 3
        wait-duration-in-open-state: 50s
        failure-rate-threshold: 50
       